### ISSUE TITLE
Build fails: aftermath-annotations are not on maven central

### ISSUE THREAD

**Issue by dimsuz** [MichaelEvans/Aftermath#16]
If I add this to my `build.gradle`:

```
compile 'org.michaelevans:aftermath:0.3.0'
apt 'org.michaelevans:aftermath-processor:0.3.0'
```

I get this error:
```
Error:Could not find Aftermath:aftermath-annotations:unspecified.
Required by:
    app:unspecified > org.michaelevans:aftermath-processor:0.3.0
    app:unspecified > org.michaelevans:aftermath:0.3.0
```

Maven Central apparently doesn't contain annotations artifact:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.michaelevans%22

**Comment by MichaelEvans** [comment]
Sorry, looks like I didn't upload the annotations artifact! I'll take a look at this tonight. My apologies for taking so long to follow up on this, I must have missed the issue in my email.

**Comment by MichaelEvans** [comment]
@dimsuz I really dropped the ball on this one - but the release is out as 0.3.1 on Maven Central now, and the artifact is available. 

My sincerest apologies for taking so long!

**Comment by dimsuz** [comment]
@MichaelEvans no problem, I didn't use this library since then, so whenever I decide to try it again, I know it is fixed now.

**Comment by dimsuz** [comment]
I guess the issue can be closed?

**Comment by MichaelEvans** [comment]
Yep, I'll close it. Sorry again!
