### ISSUE TITLE
Handle startActivityForResult for Fragments

### ISSUE THREAD

**Issue by MichaelEvans** [MichaelEvans/Aftermath#8]

**Comment by pixelbendr** [comment]
Does the library handle this?

**Comment by MichaelEvans** [comment]
@pixelbendr not quite yet - but soon! PR welcome if you want to work on it?

**Comment by burntcookie90** [comment]
Hey there @pixelbendr it seems like this works in the current release of the library.

If you're implementing `onActivityResult` in your fragment's containing activity, just make sure you call the super method as well so that unhandled request codes can be handled via the fragment.

**Comment by MichaelEvans** [comment]
I can update the docs to reflect this, thanks @burntcookie90 !

**Comment by pixelbendr** [comment]
Thanks
